messages:
  no-permissions: "&cYou don't have any permissions."
  only-players: "&cOnly players can execute this command."
  staffchat-enabled: "&aYour staffchat has been enabled."
  staffchat-disabled: "&cYour staffchat has been disabled."
  staff-message: "&8[&cStaffChat&8] %prefix%%player%&8: &7%message%"
  chat-muted: "&cThe chat is currently muted!"
  muted-chat: "&cThe chat has been muted by %player%&c!"
  unmuted-chat: "&cThe chat has been unmuted by %player%&c!"
  staffafk-enabled: "&c%player% &7is now AFK!"
  staffafk-disabled: "&c%player% &7is now back!"
  mutestaffchat-enabled: "&aYour staffchat has been muted."
  mutestaffchat-disabled: "&cYour staffchat has been unmuted."

ranks:
  owner: "&4Owner"
  admin: "&cAdmin"