name: CNStaffchat
version: '1.0-SNAPSHOT'
main: me.quartz.cnstaffchat.CNStaffchat
api-version: '1.20'
commands:
  staffchat:
    aliases:
      - sc
  mutechat:
    aliases:
      - mc
  staffafk:
  mutestaffchat:
    aliases:
      - msc
      - mutesc
  stafflist: